export const DEFAULT_BROKEN_LINK_CHECKER_PAGE_LIMIT = 10;
export const MAX_BROKEN_LINK_CHECKER_PAGE_LIMIT = 50;
export const BROKEN_LINK_CHECKER_TIMEOUT_MS = 8000;
export const BROKEN_LINK_CHECKER_MAX_REDIRECTS = 8;
